config/routes.rb
B2bplatform::Application.routes.draw do
  resources :suppliers do
    resources :products
  end

  resources :sizes

  resources :line_items do
    member do
      post :add
    end
  end
  

  get "carts/new"

  get "carts/create"

  get "carts/edit"

  get "carts/update"

  get "carts/destroy"

end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  # GET /sizes
  # GET /sizes.json
  def index
    @sizes = Size.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sizes }
    end
  end

  # GET /sizes/1
  # GET /sizes/1.json
  def show
    @size = Size.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @size }
    end
  end

  # GET /sizes/new
  # GET /sizes/new.json
  def new
    @size = Size.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @size }
    end
  end

  # GET /sizes/1/edit
  def edit
    @size = Size.find(params[:id])
  end

  # POST /sizes
  # POST /sizes.json
  def create
    @size = Size.new(params[:size])

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, notice: 'Size was successfully created.' }
        format.json { render json: @size, status: :created, location: @size }
      else
        format.html { render action: "new" }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sizes/1
  # PUT /sizes/1.json
  def update
    @size = Size.find(params[:id])

    respond_to do |format|
      if @size.update_attributes(params[:size])
        format.html { redirect_to @size, notice: 'Size was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sizes/1
  # DELETE /sizes/1.json
  def destroy
    @size = Size.find(params[:id])
    @size.destroy

    respond_to do |format|
      format.html { redirect_to sizes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/sizes/_form.html.erb
<%= form_for(@size) do |f| %>
  <% if @size.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@size.errors.count, "error") %> prohibited this size from being saved:</h2>

      <ul>
      <% @size.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sizes/edit.html.erb
<h1>Editing size</h1>

<%= render 'form' %>

<%= link_to 'Show', @size %> |
<%= link_to 'Back', sizes_path %>

app/views/sizes/index.html.erb
<h1>Listing sizes</h1>

<table>
  <tr>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sizes.each do |size| %>
  <tr>
    <td><%= size.size %></td>
    <td><%= link_to 'Show', size %></td>
    <td><%= link_to 'Edit', edit_size_path(size) %></td>
    <td><%= link_to 'Destroy', size, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Size', new_size_path %>

app/views/sizes/new.html.erb
<h1>New size</h1>

<%= render 'form' %>

<%= link_to 'Back', sizes_path %>

app/views/sizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Size:</b>
  <%= @size.size %>
</p>


<%= link_to 'Edit', edit_size_path(@size) %> |
<%= link_to 'Back', sizes_path %>