config/routes.rb
B2bplatform::Application.routes.draw do
  resources :suppliers do
    resources :products
  end

  resources :sizes

  resources :line_items do
    member do
      post :add
    end
  end
  

  get "carts/new"

  get "carts/create"

  get "carts/edit"

  get "carts/update"

  get "carts/destroy"

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_sizes
  has_many :sizes, :through => :product_sizes
  belongs_to :supplier
  attr_accessible :cost, :name, :sizes_attributes
  accepts_nested_attributes_for :sizes, :allow_destroy => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :get_supplier

  # GET /products
  # GET /products.json
  def index
    @products = @supplier.products.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = @supplier.products.find(params[:id])
    @line_item = LineItem.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = @supplier.products.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = @supplier.products.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = @supplier.products.build(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to [@supplier, @product], notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = @supplier.products.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = @supplier.products.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
  def get_supplier
    @supplier = Supplier.find(params[:supplier_id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= nested_form_for([@supplier, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <%= f.fields_for :sizes do |size_form| %>
    <%= size_form.text_field :size %>
    <%= size_form.link_to_remove "Remove this size" %>
  <% end %>
  <p>
    <%= f.link_to_add "Add a size", :sizes %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.cost %></td>
    <td><%= link_to 'Show', [product.supplier, product]%></td>
    <td><%= link_to 'Edit', edit_supplier_product_path([product.supplier, product]) %></td>
    <td><%= link_to 'Destroy', [product.supplier, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_supplier_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', supplier_products_path(@supplier) %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
Supplier: <%= @product.supplier.to_s %>
Product ID: <%= @product.id %>
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @product.cost %>
</p>

  <% @product.sizes.each do |size| %>
    <p><%= size.size %><%= text_field_tag :quantity %></p>
    <p>Product_size_id: <%= text_field_tag :product_size_id, size.product_sizes.first.id %></p>
    
  <% end %>

<%= link_to "Add to Order", add_line_item_path %>

<%= link_to 'Edit', edit_supplier_product_path([@product.supplier, @product]) %> |
<%= link_to 'Back', supplier_products_path(@product.supplier) %>